# Site
name: '黑石的知识库'
title: '黑石的知识库 - AI编程、技术分享与开发经验'
description: '黑石的知识库专注于AI编程、全栈开发、技术分享。13年开发经验，分享AI Agent开发、编程技巧、技术选型等实用内容。'
keywords: 'AI编程,全栈开发,技术博客,AI Agent,编程技巧,技术分享,黑石,开发经验'
author: '黑石'
url: 'https://blackstoneblackstone.github.io'
baseurl: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
disqus: ''
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# SEO 配置
lang: 'zh-CN'
timezone: 'Asia/Shanghai'
google_site_verification: ''  # 添加您的 Google Search Console 验证码
google_analytics: ''  # 添加您的 Google Analytics ID
google_adsense: ''  # 添加您的 Google AdSense ID

# 社交媒体
social:
  name: '黑石'
  links:
    - 'https://github.com/blackstoneblackstone'
    - 'https://twitter.com/blackstone'

# Giscus Comments
giscus:
  repo: 'blackstoneblackstone/blackstoneblackstone.github.io'
  repo_id: 'R_kgDOORMv6Q'  # 请访问 https://giscus.app/zh-CN 获取正确的 repo-id
  category: 'Announcements'
  category_id: 'DIC_kwDOORMv6c4CvOy7'  # 请访问 https://giscus.app/zh-CN 获取正确的 category-id
  mapping: 'pathname'
  strict: '0'
  reactions_enabled: '1'
  emit_metadata: '0'
  input_position: 'bottom'
  theme: 'light'
  lang: 'zh-CN'
  loading: 'lazy'

# 启用未来日期的文章
future: true

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Sitemap 配置
sitemap:
  changefreq: weekly
  priority: 0.7
  lastmod: true
  exclude: 
    - /404.html
    - /robots.txt
    - /Gemfile
    - /Gemfile.lock
    - /docker-compose.yml
  
authors:
    sal:
      name:           黑石
      site:           https://yondu.vip
      avatar:         assets/images/avatar.png
      bio:            "黑石的知识库 - 分享知识和经验"
      twitter:        https://twitter.com/blackstone

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: 黑石
      avatar: /assets/images/avatar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Disable sass converter to avoid architecture compatibility issues
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, vendor]