title: 我的博客
description: 分享技术、生活和想法
baseurl: ""
url: "https://blackstoneblackstone.github.io"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 作者信息
author:
  name: Blackstone
  email: your.email@example.com
  bio: 热爱技术，热爱生活
  location: 地球
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/blackstoneblackstone

# 社交链接
social_links:
  - label: GitHub
    icon: fab fa-github
    url: https://github.com/blackstoneblackstone

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 