title: 吉卜力小屋
description: 一个充满温暖与梦想的博客空间
baseurl: ""
url: "https://blackstoneblackstone.github.io"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 作者信息
author:
  name: Blackstone
  email: your.email@example.com
  bio: 热爱吉卜力动画，热爱生活
  location: 龙猫森林
  avatar: /assets/images/totoro-avatar.png
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/blackstoneblackstone

# 社交链接
social_links:
  - label: GitHub
    icon: fab fa-github
    url: https://github.com/blackstoneblackstone

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 主题设置
theme_settings:
  primary_color: "#7B9E87"  # 吉卜力森林绿
  secondary_color: "#F4D03F"  # 温暖黄
  accent_color: "#E74C3C"  # 吉卜力红
  background_color: "#F9F5E7"  # 温暖米色
  text_color: "#2C3E50"  # 深灰蓝

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 