title: Blackstone's Knowledge Base
description: A technical blog by a full-stack engineer, focusing on AI Agent research and technology sharing
baseurl: ""
url: "https://blackstoneblackstone.github.io"

# Languages
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localizations: ["assets", "css", "js", "images", ".git", "CNAME"]
language_names:
  en: English
  zh: 中文

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Author information
author:
  name: Blackstone
  email: your.email@example.com
  bio: Full-stack engineer with 13 years of experience, specializing in AI Agent research and development
  location: Hangzhou
  avatar: /assets/images/avatar.png
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/blackstoneblackstone
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/your-profile

# Social links
social_links:
  - label: GitHub
    icon: fab fa-github
    url: https://github.com/blackstoneblackstone
  - label: LinkedIn
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/your-profile

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Theme settings
theme_settings:
  primary_color: "#2C3E50"  # Dark blue-gray
  secondary_color: "#3498DB"  # Blue
  accent_color: "#E74C3C"  # Red
  background_color: "#FFFFFF"  # White
  text_color: "#2C3E50"  # Dark blue-gray

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 