title: 吉卜力小屋
description: 一个充满温暖与梦想的博客空间
baseurl: ""
url: "https://blackstoneblackstone.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Author information
author:
  name: Blackstone
  email: your.email@example.com
  bio: 热爱吉卜力动画，热爱生活
  location: 龙猫森林
  avatar: /assets/images/totoro-avatar.png
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/blackstoneblackstone
    - label: Twitter
      icon: fab fa-twitter
      url: https://twitter.com/yourusername
    - label: Instagram
      icon: fab fa-instagram
      url: https://instagram.com/yourusername

# Social links
social_links:
  - label: GitHub
    icon: fab fa-github
    url: https://github.com/blackstoneblackstone

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Theme settings
theme_settings:
  primary_color: "#7B9E87"  # 吉卜力森林绿
  secondary_color: "#F4D03F"  # 温暖黄
  accent_color: "#E74C3C"  # 吉卜力红
  background_color: "#F9F5E7"  # 温暖米色
  text_color: "#2C3E50"  # 深灰蓝

# Header pages
header_pages:
  - about.md
  - blog.md
  - contact.md

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/

# Extra resources
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css 