name = "blackstoneblackstone-github-io"
compatibility_date = "2024-01-01"
pages_build_output_dir = "_site"
build_command = "bundle exec jekyll build --safe --trace"
preview_build_command = "bundle exec jekyll build --safe --trace"

[vars]
RUBY_VERSION = "3.3.4"
BUNDLER_VERSION = "2.6.9"
JEKYLL_ENV = "production"
